# verification job run upon GitLab PR
gitlab-pr-build:
  only:
    - branches
  variables:
    PR_BUILD: splunk-apm
    BRANCH: $CI_COMMIT_REF_NAME
  trigger:
    project: observability/gdi/lambda-layers
    strategy: depend
